ocha_content_classification.ocha_classification_workflow.*:
  type: config_entity
  label: 'Classification Workflow.'
  mapping:
    id:
      type: string
      label: 'ID.'
    label:
      type: label
      label: 'Label.'
    limit:
      type: integer
      label: 'Maximum number of classification attempts before failure.'
    validation:
      type: mapping
      label: 'Checks to perform when validating if an entity can be classified.'
      mapping:
        empty:
          type: boolean
          label: 'Flag to indicate if the classification can proceed only when none of the classifiable or fillable field is already filled.'
    target:
      type: mapping
      label: 'Entity type and bundle this Workflow applies to.'
      mapping:
        entity_type_id:
          type: string
          label: 'Entity type ID.'
        bundle:
          type: string
          label: 'Entity bundle.'
    fields:
      type: mapping
      label: 'Analyzable and classifiable fields.'
      mapping:
        analyzable:
          type: sequence
          label: 'Analyzable fields.'
          sequence:
            type: mapping
            label: 'List of analyzable fields.'
            mapping:
              enabled:
                type: boolean
                label: 'Whether the field is enabled for content analysis or not.'
        classifiable:
          type: sequence
          label: 'Classifiable fields.'
          sequence:
            type: mapping
            label: 'List of classifiable fields.'
            mapping:
              enabled:
                type: boolean
                label: 'Whether the field is enabled for content classification or not.'
              min:
                type: integer
                label: 'Minimum number of terms to include in the classification results.'
              max:
                type: integer
                label: 'Maximum number of terms to include in the classification results.'
              hide:
                type: boolean
                label: 'Hide field in form.'
              force:
                type: boolean
                label: 'Update the field even if already filled.'
        fillable:
          type: sequence
          label: 'Fillable fields.'
          sequence:
            type: mapping
            label: 'List of fillable fields.'
            mapping:
              enabled:
                type: boolean
                label: 'Whether the field is enabled for content analysis or not.'
              properties:
                type: sequence
                label: 'List of field properties that can be filled.'
                sequence:
                  type: string
                  label: 'Field property name.'
              hide:
                type: boolean
                label: 'Hide field in form.'
              force:
                type: boolean
                label: 'Update the field even if already filled.'

    classifier:
      type: mapping
      label: 'Classifier.'
      mapping:
        id:
          type: string
          label: 'Plugin ID.'
        settings:
          type: ocha_content_classification.plugin.classifier.[%parent.id]
          label: 'Settings.'

# Classifier plugin base settings.
ocha_content_classification.plugin.classifier:
  type: mapping
  label: 'Classifier plugin base settings.'
  mapping:

# Inference classifier plugin settings.
ocha_content_classification.plugin.classifier.inference:
  type: ocha_content_classification.plugin.classifier
  label: 'Inference classifier plugin base settings.'
  mapping:
    analyzable:
      type: mapping
      label: 'Analyzable Content.'
      mapping:
        fields:
          type: sequence
          label: 'Analyzable fields.'
          sequence:
            type: mapping
            mapping:
              placeholder:
                type: string
                label: 'Placeholder to use in the prompt.'
              processor:
                type: string
                label: 'Processor.'
              file:
                type: boolean
                label: 'Indicates if the content of the field should be passed as files to the model.'
    classifiable:
      type: mapping
      label: 'Classifiable Content.'
      mapping:
        fields:
          type: sequence
          label: 'Classifiable fields.'
          sequence:
            type: mapping
            mapping:
              placeholder:
                type: string
                label: 'Placeholder to use in the prompt.'
              property:
                 type: string
                 label: 'Property to use for the mapping in the prompt if there are too many terms to allow overrides.'
              terms:
                type: sequence
                label: 'Term overrides.'
                sequence:
                  type: string
                  label: 'Term description.'
    fillable:
      type: mapping
      label: 'Fillable Content.'
      mapping:
        fields:
          type: sequence
          label: 'Fillable field properties.'
          sequence:
            type: mapping
            mapping:
              placeholder:
                type: string
                label: 'Placeholder to use in the prompt.'
    inference:
      type: mapping
      label: 'Inference settings.'
      mapping:
        plugin_id:
          type: string
          label: 'OCHA AI completion plugin ID.'
        temperature:
          type: float
          label: 'Temperature.'
        top_p:
          type: float
          label: 'Nucleus sampling (top_p).'
        max_tokens:
          type: integer
          label: 'Max tokens.'
        system_prompt:
          type: text
          label: 'System prompt.'
        prompt:
          type: text
          label: 'Prompt.'
